/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author User
 */
public class DatabaseApp1 extends javax.swing.JFrame {
     DBHandler db = new DBHandler();
     private String[] col_names;
     private int col_no;
     
     
    /**
     * Creates new form DatabaseApp1
     */
    public DatabaseApp1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        leftPane = new javax.swing.JPanel();
        hoverPane4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        hoverPane1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        show_data = new javax.swing.JLabel();
        hoverPane2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        insert = new javax.swing.JLabel();
        hoverPane3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        table_box = new javax.swing.JComboBox<>();
        hoverPane5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        set_connection = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        titlePane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        col_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        col_value = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        up_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        up_value = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        col_name1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        col_value1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        find = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bus_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pass_id = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        destination = new javax.swing.JTextField();
        find_det = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPane.setBackground(new java.awt.Color(54, 33, 89));
        leftPane.setForeground(new java.awt.Color(255, 255, 255));
        leftPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hoverPane4.setBackground(new java.awt.Color(65, 43, 100));
        hoverPane4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverPane4MouseMoved(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/search.png"))); // NOI18N

        search.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Seat Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hoverPane4Layout = new javax.swing.GroupLayout(hoverPane4);
        hoverPane4.setLayout(hoverPane4Layout);
        hoverPane4Layout.setHorizontalGroup(
            hoverPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        hoverPane4Layout.setVerticalGroup(
            hoverPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftPane.add(hoverPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 60));

        hoverPane1.setBackground(new java.awt.Color(65, 43, 100));
        hoverPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverPane1MouseMoved(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/show.png"))); // NOI18N

        show_data.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        show_data.setForeground(new java.awt.Color(255, 255, 255));
        show_data.setText("Show Info");
        show_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show_dataMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hoverPane1Layout = new javax.swing.GroupLayout(hoverPane1);
        hoverPane1.setLayout(hoverPane1Layout);
        hoverPane1Layout.setHorizontalGroup(
            hoverPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_data, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        hoverPane1Layout.setVerticalGroup(
            hoverPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftPane.add(hoverPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 60));

        hoverPane2.setBackground(new java.awt.Color(65, 43, 100));
        hoverPane2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverPane2MouseMoved(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/insert.png"))); // NOI18N

        insert.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Information Insertion");
        insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insertMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hoverPane2Layout = new javax.swing.GroupLayout(hoverPane2);
        hoverPane2.setLayout(hoverPane2Layout);
        hoverPane2Layout.setHorizontalGroup(
            hoverPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        hoverPane2Layout.setVerticalGroup(
            hoverPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftPane.add(hoverPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 60));

        hoverPane3.setBackground(new java.awt.Color(65, 43, 100));
        hoverPane3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverPane3MouseMoved(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/update.png"))); // NOI18N

        update.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update Info");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hoverPane3Layout = new javax.swing.GroupLayout(hoverPane3);
        hoverPane3.setLayout(hoverPane3Layout);
        hoverPane3Layout.setHorizontalGroup(
            hoverPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        hoverPane3Layout.setVerticalGroup(
            hoverPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftPane.add(hoverPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 60));

        table_box.setBackground(new java.awt.Color(204, 204, 255));
        table_box.setForeground(new java.awt.Color(255, 255, 255));
        leftPane.add(table_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 30));

        hoverPane5.setBackground(new java.awt.Color(65, 43, 100));
        hoverPane5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverPane5MouseMoved(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete.png"))); // NOI18N

        delete.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hoverPane5Layout = new javax.swing.GroupLayout(hoverPane5);
        hoverPane5.setLayout(hoverPane5Layout);
        hoverPane5Layout.setHorizontalGroup(
            hoverPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        hoverPane5Layout.setVerticalGroup(
            hoverPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftPane.add(hoverPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 60));

        set_connection.setBackground(new java.awt.Color(102, 102, 255));
        set_connection.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        set_connection.setForeground(new java.awt.Color(255, 255, 255));
        set_connection.setText("Connect");
        set_connection.setBorder(null);
        set_connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_connectionActionPerformed(evt);
            }
        });
        leftPane.add(set_connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 30));

        back.add(leftPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/close.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        back.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 50));

        data_table.setBackground(new java.awt.Color(204, 204, 204));
        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(data_table);

        back.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 670, 290));

        titlePane.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cloumn Name");

        col_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_nameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Column Value");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(col_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(col_value, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col_value, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Delete", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 102, 255));

        jLabel13.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Update Name");

        jLabel14.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Update Value");

        up_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_valueActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cloumn Name");

        col_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_name1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Column Value");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(up_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(up_value, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(up_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(up_value, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Update", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(find, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Schedule", jPanel4);

        jLabel4.setText("Bus ID :");

        jLabel6.setText("Passenger ID: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bus_id, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass_id, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pass_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bus_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Find Seat", jPanel5);

        jLabel8.setText("Destination");

        find_det.setText("View");
        find_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_detActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(find_det, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destination)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(find_det)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Journey", jPanel6);

        titlePane.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 173, 670, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/name.png"))); // NOI18N
        titlePane.add(jLabel2);
        jLabel2.setBounds(134, 44, 436, 71);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/bus.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        titlePane.add(jLabel12);
        jLabel12.setBounds(10, 0, 670, 200);

        back.add(titlePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, -3, 680, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void up_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_valueActionPerformed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel9MousePressed

    private void hoverPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverPane1MouseMoved
        setColor(hoverPane1);
        resetColor(hoverPane2);
        resetColor(hoverPane3);
        resetColor(hoverPane4);
        resetColor(hoverPane5);
    }//GEN-LAST:event_hoverPane1MouseMoved

    private void hoverPane2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverPane2MouseMoved
        setColor(hoverPane2);
        resetColor(hoverPane1);
        resetColor(hoverPane3);
        resetColor(hoverPane4);
        resetColor(hoverPane5);
    }//GEN-LAST:event_hoverPane2MouseMoved

    private void hoverPane3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverPane3MouseMoved
        setColor(hoverPane3);
        resetColor(hoverPane1);
        resetColor(hoverPane2);
        resetColor(hoverPane4);
        resetColor(hoverPane5);
    }//GEN-LAST:event_hoverPane3MouseMoved

    private void hoverPane4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverPane4MouseMoved
        setColor(hoverPane4);
        resetColor(hoverPane1);
        resetColor(hoverPane2);
        resetColor(hoverPane3);
        resetColor(hoverPane5);
    }//GEN-LAST:event_hoverPane4MouseMoved

    private void hoverPane5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverPane5MouseMoved
        setColor(hoverPane5);
        resetColor(hoverPane1);
        resetColor(hoverPane2);
        resetColor(hoverPane3);
        resetColor(hoverPane4);
    }//GEN-LAST:event_hoverPane5MouseMoved

    private void col_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_col_nameActionPerformed

    private void show_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_dataMousePressed
        
        DefaultTableModel model = (DefaultTableModel) data_table.getModel();                
        model.setColumnCount(0);
        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount() ; i++){                
                model.removeRow(i);
            }
        }
        
        ResultSet result = db.testQuery(table_box.getSelectedItem().toString());
        
        //For Column Name
        ArrayList<String> col = db.columnName(result);
             
            for(String cc : col){
                //System.out.print(cc+" ");
                model.addColumn(cc);                
            }
            //System.out.println("");
            
        //For Insert Data    
        col_no = data_table.getColumnCount();        
        col_names = new String[col_no + 1];
        
        JTableHeader th = data_table.getTableHeader();        
        TableColumnModel tcm = th.getColumnModel();
        
        for(int x = 0, y = tcm.getColumnCount(); x < y; x++)
        {
          TableColumn tc = tcm.getColumn(x);
          col_names[x] =  tc.getHeaderValue().toString();
        }            
        //For Column Data
        ArrayList<ArrayList<String>> records = db.getResult(result);
        
        for(int i = 0 ; i < records.size() ; i ++){
            model.addRow(records.get(i).toArray());
        }
        data_table.repaint();              
    }//GEN-LAST:event_show_dataMousePressed

    private void insertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMousePressed
        String tName = table_box.getSelectedItem().toString();        
        InsertData ob = new InsertData(tName, col_no ,col_names);
        
        ob.setVisible(true);
    }//GEN-LAST:event_insertMousePressed

    private void set_connectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_connectionActionPerformed
        db.setConnection("bus", "root", "");
        
        ArrayList<String> res = db.tableName();
        for(String s : res){
            //System.out.println(s);
            table_box.addItem(s);
        }         
        JOptionPane.showMessageDialog(null, "Successully Connected to Database");
    }//GEN-LAST:event_set_connectionActionPerformed

    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        String tName = table_box.getSelectedItem().toString();
        String column_name = col_name.getText();
        String column_value = col_value.getText();
        db.deleteRowQuery(tName, column_name, column_value);
    }//GEN-LAST:event_deleteMousePressed

    private void updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMousePressed
        String tName = table_box.getSelectedItem().toString();
        String column1_name = col_name1.getText();
        String column1_value = col_value1.getText();
        String column2_name = up_name.getText();
        String column2_value = up_value.getText();
        db.updateQuery(tName, column1_name, column1_value, column2_name, column2_value);
    }//GEN-LAST:event_updateMousePressed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        DefaultTableModel model = (DefaultTableModel) data_table.getModel();                
        String tName = table_box.getSelectedItem().toString();
        
        model.setColumnCount(0);
        
        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount() ; i++){                
                model.removeRow(i);
            }
        }                         
        ResultSet result = db.searchQuery(bus_id.getText(),pass_id.getText());
        
        ArrayList<String> col = db.columnName(result);
             
            for(String cc : col){
                //System.out.print(cc+" ");
                model.addColumn(cc);                
            }
                        
        ArrayList<ArrayList<String>> records = db.getResult(result);
        
        for(int i = 0 ; i < records.size() ; i ++){
            model.addRow(records.get(i).toArray());
        }
        data_table.repaint();
        
        /*InsertData ob = new InsertData(tName, col_no ,col_names);
        
        ob.setVisible(true);
        
        model.setColumnCount(0);
        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount() ; i++){                
                model.removeRow(i);
            }
        }
        
        ResultSet result = db.rs;
        
        ArrayList<String> col = db.columnName(result);
                             
            for(String cc : col){
                //System.out.print(cc+" ");
                model.addColumn(cc);                
            }
                        
        ArrayList<ArrayList<String>> records = db.getResult(result);
        
        for(int i = 0 ; i < records.size() ; i ++){
            model.addRow(records.get(i).toArray());
        }
        data_table.repaint();*/
    }//GEN-LAST:event_searchMousePressed

    private void col_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_col_name1ActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(jDateChooser1.getDate());
        System.out.println(theDate);
        
        String tName = table_box.getSelectedItem().toString();
        
        DefaultTableModel model = (DefaultTableModel) data_table.getModel();
        
        model.setColumnCount(0);
        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount() ; i++){                
                model.removeRow(i);
            }
        }                         
        ResultSet result = db.findQuery(tName,theDate);
        
        ArrayList<String> col = db.columnName(result);
             
            for(String cc : col){
                //System.out.print(cc+" ");
                model.addColumn(cc);                
            }
                        
        ArrayList<ArrayList<String>> records = db.getResult(result);
        
        for(int i = 0 ; i < records.size() ; i ++){
            model.addRow(records.get(i).toArray());
        }
        data_table.repaint();
    }//GEN-LAST:event_findActionPerformed

    private void find_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_detActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(jDateChooser2.getDate());
        System.out.println(theDate);
        
        //String tName = table_box.getSelectedItem().toString();
        
        DefaultTableModel model = (DefaultTableModel) data_table.getModel();
        
        model.setColumnCount(0);
        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount() ; i++){                
                model.removeRow(i);
            }
        }                         
        ResultSet result = db.findBusQuery(theDate,destination.getText());
        
        ArrayList<String> col = db.columnName(result);
             
            for(String cc : col){
                //System.out.print(cc+" ");
                model.addColumn(cc);                
            }
                        
        ArrayList<ArrayList<String>> records = db.getResult(result);
        
        for(int i = 0 ; i < records.size() ; i ++){
            model.addRow(records.get(i).toArray());
        }
        data_table.repaint();
        
    }//GEN-LAST:event_find_detActionPerformed
    
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(65,43,100));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseApp1().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JTextField bus_id;
    private javax.swing.JTextField col_name;
    private javax.swing.JTextField col_name1;
    private javax.swing.JTextField col_value;
    private javax.swing.JTextField col_value1;
    public javax.swing.JTable data_table;
    private javax.swing.JLabel delete;
    private javax.swing.JTextField destination;
    private javax.swing.JButton find;
    private javax.swing.JButton find_det;
    private javax.swing.JPanel hoverPane1;
    private javax.swing.JPanel hoverPane2;
    private javax.swing.JPanel hoverPane3;
    private javax.swing.JPanel hoverPane4;
    private javax.swing.JPanel hoverPane5;
    private javax.swing.JLabel insert;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel leftPane;
    private javax.swing.JTextField pass_id;
    private javax.swing.JLabel search;
    private javax.swing.JButton set_connection;
    private javax.swing.JLabel show_data;
    private javax.swing.JComboBox<String> table_box;
    private javax.swing.JPanel titlePane;
    private javax.swing.JTextField up_name;
    private javax.swing.JTextField up_value;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
